,py,py,31.12.2017 18:19,file:///home/py/.config/libreoffice/4;